/* ============================================================================
 * STORE — one mutable working copy of the scenario, plus session state.
 *
 * Screens never hold their own numbers. They subscribe, read derived values
 * through the selectors below, and re-render when anything changes. Confirming
 * a bag at intake therefore moves the donor's progress bar and the
 * coordinator's coverage figure in the same tick, because there is only one
 * number to move.
 * ==========================================================================*/
const Store = (function () {
  'use strict';

  const clone = obj => JSON.parse(JSON.stringify(obj));

  const listeners = [];
  let state = {
    scenarioId: 'tolima',
    data: clone(SCENARIOS.tolima),
    lang: 'en',
    role: 'donor',
    screen: null,
    siteId: 'libano',        // the centre the current staff user is working at
    online: true,            // simulated connectivity
    queue: [],               // actions taken while offline, awaiting sync
    donor: null,             // in-progress donation draft
    vouchers: [],            // generated by the matching engine
    log: [],                 // session activity, newest first
    trained: {},             // training badges earned in this session
    impact: []               // donor-visible events
  };

  function get() { return state; }

  function subscribe(fn) { listeners.push(fn); return () => {
    const i = listeners.indexOf(fn); if (i >= 0) listeners.splice(i, 1);
  }; }

  function emit() { listeners.forEach(fn => fn(state)); }

  /** Mutate state through a function, then notify. */
  function update(fn) {
    fn(state);
    emit();
  }

  function setScenario(id) {
    if (!SCENARIOS[id]) return;
    const preferred = SCENARIOS[id].preferredLang;
    state.scenarioId = id;
    state.data = clone(SCENARIOS[id]);
    state.siteId = SCENARIOS[id].sites[0].id;
    state.vouchers = [];
    state.queue = [];
    state.donor = null;
    state.log = [];
    state.impact = [];
    // Follow the scenario's own language unless the user has pinned one.
    if (!state.langPinned) state.lang = preferred;
    emit();
  }

  function setLang(lang, pinned) {
    state.lang = lang;
    if (pinned) state.langPinned = true;
    try { localStorage.setItem('capem.lang', lang); } catch (e) { /* private mode */ }
    emit();
  }

  /* -------------------------------------------------------------------------
   * Actions. Each one is small, named after what a person actually does, and
   * routed through queueOrApply so the offline behaviour is real rather than
   * described.
   * -----------------------------------------------------------------------*/
  function queueOrApply(action) {
    if (state.online) {
      action.apply(state);
      logEvent(action.label, 'synced');
    } else {
      action.apply(state);               // optimistic local write
      state.queue.push(action);
      logEvent(action.label, 'queued');
    }
    emit();
  }

  function logEvent(label, status) {
    state.log.unshift({ label, status, at: nowClock() });
    if (state.log.length > 40) state.log.pop();
  }

  function sync() {
    const n = state.queue.length;
    state.queue = [];
    state.log.forEach(e => { if (e.status === 'queued') e.status = 'synced'; });
    emit();
    return n;
  }

  function setOnline(v) { state.online = v; emit(); }

  /** Books stock in at a site. Used by pass confirmation and walk-in intake. */
  function receiveStock(siteId, itemCode, qty, label) {
    queueOrApply({
      label: label,
      apply(s) {
        const row = s.data.stock.find(r => r.site === siteId && r.item === itemCode);
        if (row) row.onHand += qty;
        else s.data.stock.push({ site: siteId, item: itemCode, onHand: qty, min: 0, incoming: 0 });
        s.data.movements.unshift({
          time: nowClock(), type: 'in', item: itemCode, qty: qty,
          site: siteId, src: 'pass', ref: label, by: 'this session'
        });
      }
    });
  }

  function issueVoucher(voucher) {
    queueOrApply({
      label: 'Voucher ' + voucher.ref,
      apply(s) {
        // Reserve the stock now. A voucher that cannot be honoured is worse
        // than no voucher, so reservation happens at issue, not at handover.
        voucher.lines.forEach(line => {
          const row = s.data.stock.find(r => r.site === voucher.site && r.item === line.item);
          if (row) row.reserved = (row.reserved || 0) + line.qty;
        });
        s.vouchers.push(voucher);
      }
    });
  }

  function fulfilVoucher(ref) {
    queueOrApply({
      label: 'Handover ' + ref,
      apply(s) {
        const v = s.vouchers.find(x => x.ref === ref);
        if (!v || v.status === 'fulfilled') return;
        v.status = 'fulfilled';
        v.fulfilledAt = nowClock();
        v.lines.forEach(line => {
          const row = s.data.stock.find(r => r.site === v.site && r.item === line.item);
          if (row) {
            row.onHand -= line.qty;
            row.reserved = Math.max(0, (row.reserved || 0) - line.qty);
          }
          s.data.movements.unshift({
            time: nowClock(), type: 'out', item: line.item, qty: -line.qty,
            site: v.site, src: 'dist', ref: v.ref, by: 'gate'
          });
        });
        const fam = s.data.families.find(f => f.ref === v.family);
        if (fam) {
          v.lines.forEach(l => { fam.received[l.item] = (fam.received[l.item] || 0) + l.qty; });
          fam.daysWaiting = 0;
        }
        // The donor impact feed is a by-product of this handover, not a
        // separate reporting step. That is the whole point.
        s.impact.unshift({ kind: 'distributed', ref: v.ref, site: v.site, lines: v.lines, at: nowClock() });
      }
    });
  }

  function registerFamily(fam) {
    queueOrApply({
      label: 'Registered ' + fam.ref,
      apply(s) { s.data.families.push(fam); }
    });
  }

  function setNeedPriority(siteId, item, priority) {
    update(s => {
      const n = s.data.needs.find(x => x.site === siteId && x.item === item);
      if (n) n.priority = priority;
    });
  }

  function setNeedPublished(siteId, item, published) {
    update(s => {
      const n = s.data.needs.find(x => x.site === siteId && x.item === item);
      if (n) n.published = published;
    });
  }

  function nowClock() {
    const d = new Date();
    return String(d.getHours()).padStart(2, '0') + ':' + String(d.getMinutes()).padStart(2, '0');
  }

  return {
    get, subscribe, update, setScenario, setLang, setOnline, sync,
    receiveStock, issueVoucher, fulfilVoucher, registerFamily,
    setNeedPriority, setNeedPublished, logEvent, nowClock, queueOrApply
  };
})();

/* ============================================================================
 * SELECTORS — every number shown anywhere is computed here, once.
 * ==========================================================================*/
const Sel = (function () {
  'use strict';

  const d = () => Store.get().data;

  function item(code) { return CATALOG.find(c => c.code === code); }

  function itemName(code) {
    const it = item(code);
    return it ? it.name[LANG_INDEX[Store.get().lang]] : code;
  }

  function itemUnit(code) {
    const it = item(code);
    return it ? it.unit[LANG_INDEX[Store.get().lang]] : '';
  }

  function site(id) { return d().sites.find(s => s.id === id); }
  function sites() { return d().sites; }

  function stockRow(siteId, code) {
    return d().stock.find(r => r.site === siteId && r.item === code)
      || { site: siteId, item: code, onHand: 0, min: 0, incoming: 0, reserved: 0 };
  }

  function available(siteId, code) {
    const r = stockRow(siteId, code);
    return Math.max(0, r.onHand - (r.reserved || 0));
  }

  /** Event-wide totals for one item, across every site. */
  function eventStock(code) {
    return d().stock.filter(r => r.item === code)
      .reduce((acc, r) => ({
        onHand: acc.onHand + r.onHand,
        incoming: acc.incoming + (r.incoming || 0),
        reserved: acc.reserved + (r.reserved || 0)
      }), { onHand: 0, incoming: 0, reserved: 0 });
  }

  function eventTarget(code) {
    return d().needs.filter(n => n.item === code).reduce((a, n) => a + n.target, 0);
  }

  /** Needs enriched with live coverage. This is the join everything else uses. */
  function needs(opts) {
    opts = opts || {};
    let list = d().needs.slice();
    if (opts.site) list = list.filter(n => n.site === opts.site);
    if (opts.publishedOnly) list = list.filter(n => n.published);
    return list.map(n => {
      const st = stockRow(n.site, n.item);
      const have = st.onHand;
      const pct = n.target > 0 ? Math.min(100, Math.round((have / n.target) * 100)) : 100;
      return Object.assign({}, n, {
        have: have,
        incoming: st.incoming || 0,
        pct: pct,
        status: pct >= 95 ? 'good' : pct >= 60 ? 'warning' : pct >= 30 ? 'serious' : 'critical',
        belowMin: have < st.min
      });
    }).sort((a, b) => PRIORITY_ORDER[a.priority] - PRIORITY_ORDER[b.priority] || a.pct - b.pct);
  }

  /** One number a coordinator is actually asked for: are we covered? */
  function coverage(siteId) {
    const list = needs(siteId ? { site: siteId } : {});
    if (!list.length) return 0;
    const totalTarget = list.reduce((a, n) => a + n.target, 0);
    const totalHave = list.reduce((a, n) => a + Math.min(n.have, n.target), 0);
    return totalTarget ? Math.round((totalHave / totalTarget) * 100) : 0;
  }

  function families(siteId) {
    return siteId ? d().families.filter(f => f.site === siteId) : d().families;
  }

  function shelterFor(siteId) {
    const s = site(siteId);
    return s && s.shelter ? s.shelter : null;
  }

  function peopleCount(siteId) {
    return families(siteId).reduce((a, f) => a + f.size, 0);
  }

  function under5Count(siteId) {
    return families(siteId).reduce((a, f) => a + f.under5, 0);
  }

  function alerts(siteId) {
    const out = [];
    d().stock.forEach(r => {
      if (siteId && r.site !== siteId) return;
      if (r.onHand < r.min) {
        out.push({ level: 'critical', kind: 'belowMin', site: r.site, item: r.item,
                   onHand: r.onHand, min: r.min, incoming: r.incoming || 0 });
      }
      if (r.expiring) {
        out.push({ level: 'warning', kind: 'expiring', site: r.site, item: r.item, qty: r.expiring });
      }
    });
    needs(siteId ? { site: siteId } : {}).forEach(n => {
      if (n.pct >= 95 && n.published) {
        out.push({ level: 'warning', kind: 'surplus', site: n.site, item: n.item, pct: n.pct });
      }
    });
    const sh = siteId ? shelterFor(siteId) : null;
    if (sh && sh.occupied / sh.spots > 0.75) {
      out.push({ level: 'warning', kind: 'capacity', site: siteId,
                 pct: Math.round((sh.occupied / sh.spots) * 100) });
    }
    return out.sort((a, b) => (a.level === 'critical' ? -1 : 1) - (b.level === 'critical' ? -1 : 1));
  }

  /** Items this site is currently asking for, by category, for donor steering. */
  function wantedCategories(siteId) {
    const set = new Set();
    needs({ site: siteId, publishedOnly: true }).forEach(n => {
      if (n.pct < 95) { const it = item(n.item); if (it) set.add(it.cat); }
    });
    return [...set];
  }

  /** Ranks centres by how well they match what the donor has actually packed. */
  function suggestCentres(categories) {
    return sites().map(s => {
      const wanted = needs({ site: s.id, publishedOnly: true }).filter(n => n.pct < 95);
      let score = 0;
      const matched = [];
      wanted.forEach(n => {
        const it = item(n.item);
        if (!it) return;
        if (categories.includes(it.cat)) {
          const urgency = PRIORITY_WEIGHT[n.priority] || 1;
          const gap = 1 - n.pct / 100;
          score += urgency * gap * 10;
          matched.push(n.item);
        }
      });
      return { site: s, score: Math.round(score), matched: matched };
    }).sort((a, b) => b.score - a.score);
  }

  function volunteers() { return d().volunteers; }
  function shifts() { return d().shifts; }
  function movements() { return d().movements; }
  function stats() { return d().stats; }
  function event() { return d().event; }
  function currency() { return d().currency; }

  return {
    item, itemName, itemUnit, site, sites, stockRow, available, eventStock, eventTarget,
    needs, coverage, families, shelterFor, peopleCount, under5Count, alerts,
    wantedCategories, suggestCentres, volunteers, shifts, movements, stats, event, currency
  };
})();

const PRIORITY_ORDER = { critical: 0, high: 1, medium: 2, low: 3 };
const PRIORITY_WEIGHT = { critical: 3, high: 2, medium: 1, low: 0.5 };
const LANG_INDEX = { en: 0, es: 1, pt: 2 };
